server:
  port: 8090
debug: true
logging:
  level:
    tk:
      mybatis: TRACE
    com:
      wjl: trace
    org:
      springframework:
          web: INFO
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/innovation
    username: root
    password: 123456
    initialSize: 1
    minIdle: 1
    maxActive: 20
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
  mvc:
    favicon:
      enabled: false
  http:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
mybatis:
  type-aliases-package: com.wjl.model
  mapper-locations: classpath:maper/*.xml
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect:  mysql
  reasonable: true
  support-methods-arguments: true
  params: count\=countSql
upload:
  src: 11112222



